# Example config for a tiny demo model and synthetic dataset
model:
  type: "mlp"
  input_dim: 64
  hidden_dim: 128
  output_dim: 10
train:
  epochs: 5
  batch_size: 32
  lr: 0.001
  seed: 42
dataset:
  type: "synthetic"
  size: 1000
  val_split: 0.2
output:
  dir: "outputs"
